/**
 * Course lessons — one mini-board per Commit Chess button.
 * Marks: from, to, target, staged, merge, hop, ghost (after-state silhouette)
 */

export const TUTORIAL_LESSONS = [
  {
    id: 'flow',
    title: 'How a turn works',
    button: 'Core loop',
    summary: 'Every normal move is three clicks on the buttons/board: add → commit → push.',
    steps: [
      'Select one of your logo pieces on the big board.',
      'Click a green target square (that is git add — staging).',
      'Press git commit (optional message), then git push to apply and end your turn.',
    ],
    size: 5,
    cells: [
      { r: 4, c: 1, side: 'you', kind: 'p', mark: 'from' },
      { r: 3, c: 1, mark: 'target' },
      { r: 2, c: 1, mark: 'to' },
      { r: 0, c: 3, side: 'opponent', kind: 'k' },
      { r: 4, c: 3, side: 'you', kind: 'k' },
    ],
    caption: 'Gold = selected piece. Green = legal stage target. Blue later = staged path.',
  },
  {
    id: 'add',
    title: 'git add',
    button: 'git add',
    summary: 'Stages a move. Does not move the piece yet — it only prepares the change.',
    steps: [
      'Make sure git add is the active mode (highlighted).',
      'Click your piece, then click a legal green square.',
      'Those two squares turn blue: the move is staged.',
    ],
    size: 5,
    cells: [
      { r: 4, c: 2, side: 'you', kind: 'r', mark: 'from' },
      { r: 1, c: 2, mark: 'target' },
      { r: 2, c: 2, mark: 'target' },
      { r: 3, c: 2, mark: 'target' },
      { r: 0, c: 0, side: 'opponent', kind: 'p' },
      { r: 4, c: 4, side: 'you', kind: 'k' },
    ],
    caption: 'Rook slides; green cells show where git add can stage.',
  },
  {
    id: 'commit',
    title: 'git commit',
    button: 'git commit',
    summary: 'Locks in the staged move with a message. Still does not change the board until push.',
    steps: [
      'After a blue staged path appears, type a short message (optional).',
      'Press git commit.',
      'The commit log records your message; board still waits for push.',
    ],
    size: 5,
    cells: [
      { r: 4, c: 1, side: 'you', kind: 'p', mark: 'staged' },
      { r: 3, c: 1, mark: 'staged' },
      { r: 4, c: 3, side: 'you', kind: 'k' },
      { r: 0, c: 2, side: 'opponent', kind: 'k' },
    ],
    caption: 'Blue pair = staged. Commit names the change; push applies it.',
  },
  {
    id: 'push',
    title: 'git push',
    button: 'git push',
    summary: 'Applies the staged commit to the board and ends your turn (AI moves next).',
    steps: [
      'With a staged (and preferably committed) move, press git push.',
      'Your piece jumps to the target; captures remove the Other Cursor piece.',
      'Turn passes to the Other Cursor AI.',
    ],
    size: 5,
    cells: [
      { r: 4, c: 1, mark: 'from' },
      { r: 2, c: 1, side: 'you', kind: 'p', mark: 'to' },
      { r: 4, c: 3, side: 'you', kind: 'k' },
      { r: 0, c: 2, side: 'opponent', kind: 'k' },
    ],
    caption: 'After push: piece sits on the destination; origin is empty.',
  },
  {
    id: 'rebase',
    title: 'git rebase',
    button: 'git rebase',
    summary: 'Special move: knight-hop from the selected piece, then stage that hop for commit/push.',
    steps: [
      'Press git rebase so hop mode is active.',
      'Select your piece, then click a knight-shaped landing square.',
      'Finish with git commit and git push like a normal staged move.',
    ],
    size: 5,
    cells: [
      { r: 4, c: 1, side: 'you', kind: 'n', mark: 'from' },
      { r: 2, c: 2, mark: 'hop' },
      { r: 2, c: 0, mark: 'hop' },
      { r: 3, c: 3, mark: 'hop' },
      { r: 0, c: 4, side: 'opponent', kind: 'p' },
      { r: 4, c: 4, side: 'you', kind: 'k' },
    ],
    caption: 'Purple = knight-hop landings (rebase targets).',
  },
  {
    id: 'merge',
    title: 'git merge',
    button: 'git merge',
    summary: 'Combine an adjacent friendly piece into the selected one (upgrades strength) and pass the turn.',
    steps: [
      'Press git merge.',
      'Select one of your pieces, then click an orthogonally adjacent friendly piece.',
      'The neighbor is absorbed; your piece may upgrade (pawn→knight→rook→queen).',
    ],
    size: 5,
    cells: [
      { r: 3, c: 2, side: 'you', kind: 'p', mark: 'from' },
      { r: 3, c: 3, side: 'you', kind: 'p', mark: 'merge' },
      { r: 4, c: 2, side: 'you', kind: 'k' },
      { r: 0, c: 2, side: 'opponent', kind: 'k' },
    ],
    caption: 'Orange neighbor = merge target into the gold selected piece.',
  },
  {
    id: 'cherry-pick',
    title: 'git cherry-pick',
    button: 'git cherry-pick',
    summary: 'Replay the Other Cursor’s last move delta from your selected piece, if that landing is legal.',
    steps: [
      'Wait until the AI has pushed at least one move (it appears in the commit log).',
      'Select your piece, then press git cherry-pick.',
      'If the same row/column delta is legal, it stages — then commit and push.',
    ],
    size: 5,
    cells: [
      { r: 1, c: 1, mark: 'from' },
      { r: 1, c: 3, mark: 'to' },
      { r: 3, c: 1, side: 'you', kind: 'b', mark: 'from' },
      { r: 3, c: 3, mark: 'target' },
      { r: 4, c: 4, side: 'you', kind: 'k' },
      { r: 0, c: 0, side: 'opponent', kind: 'k' },
    ],
    caption: 'Ghost arrows: AI moved →; your cherry-pick copies that delta.',
  },
  {
    id: 'revert',
    title: 'git revert',
    button: 'git revert',
    summary: 'Once per game: restore the board to just before the last capture.',
    steps: [
      'Only works after a capture has been pushed (yours or AI).',
      'Press git revert to restore that earlier position.',
      'You get the turn again; revert cannot be used a second time.',
    ],
    size: 5,
    cells: [
      { r: 2, c: 2, side: 'you', kind: 'q', mark: 'to' },
      { r: 4, c: 4, mark: 'from' },
      { r: 4, c: 1, side: 'you', kind: 'k' },
      { r: 0, c: 3, side: 'opponent', kind: 'k' },
    ],
    caption: 'Revert rewinds a capture — like undoing a bad commit on the board.',
  },
  {
    id: 'reset-soft',
    title: 'git reset',
    button: 'git reset',
    summary: 'Clears the staging area without moving pieces. Safe “never mind” for a staged path.',
    steps: [
      'If you staged the wrong square (blue path), press git reset.',
      'Staging clears; pieces stay where they were.',
      'Select again and git add a different target.',
    ],
    size: 5,
    cells: [
      { r: 4, c: 2, side: 'you', kind: 'b', mark: 'from' },
      { r: 1, c: 2, mark: 'staged' },
      { r: 4, c: 4, side: 'you', kind: 'k' },
      { r: 0, c: 0, side: 'opponent', kind: 'k' },
    ],
    caption: 'Blue staging wiped by reset — piece never left the gold square.',
  },
  {
    id: 'select-piece',
    title: 'Selecting a piece',
    button: 'Board click',
    summary: 'Your pieces use the Unofficial Cursor News logo. The Other Cursor uses the flipped/light logo.',
    steps: [
      'Only your logos move on your turn.',
      'Gold outline = selected.',
      'Green outline = legal target for the current mode.',
    ],
    size: 5,
    cells: [
      { r: 4, c: 0, side: 'you', kind: 'r' },
      { r: 4, c: 1, side: 'you', kind: 'n', mark: 'from' },
      { r: 4, c: 2, side: 'you', kind: 'b' },
      { r: 4, c: 3, side: 'you', kind: 'q' },
      { r: 4, c: 4, side: 'you', kind: 'k' },
      { r: 0, c: 2, side: 'opponent', kind: 'k' },
      { r: 1, c: 2, side: 'opponent', kind: 'p' },
    ],
    caption: 'Same logo skin for every piece type — position and moves still follow chess-like rules.',
  },
  {
    id: 'puzzles',
    title: 'Puzzles vs free play',
    button: 'Mode row',
    summary: 'Use the mode buttons above the board for guided set-games, or Free play for a full match vs AI.',
    steps: [
      'Commit the capture — stage a queen take on the enemy king, then push.',
      'Rebase hop — practice knight-hop staging.',
      'Merge up — merge two pawns, then continue hunting.',
    ],
    size: 5,
    cells: [
      { r: 4, c: 2, side: 'you', kind: 'q', mark: 'from' },
      { r: 0, c: 2, side: 'opponent', kind: 'k', mark: 'to' },
      { r: 4, c: 4, side: 'you', kind: 'k' },
    ],
    caption: 'Puzzle boards start simpler so each button skill can be practiced alone.',
  },
];
